repos:
  - repo: https://github.com/datarootsio/databooks
    rev: 1.3.0
    hooks:
      - id: databooks-meta
        name: databooks-meta
        description: "Remove Jupyter notebook metadata using `databooks`."
        files: notebooks/

  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
        files: src-mlflow-project/

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ["--line-length", "88"]
        files: src-mlflow-project/

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-bandit", "flake8-bugbear"]
        files: src-mlflow-project/