repos:
  - repo: https://github.com/datarootsio/databooks
    rev: 1.0.5
    hooks:
      - id: databooks-meta
        name: databooks-meta
        description: "Remove Jupyter notebook metadata using `databooks`."
        entry: databooks meta --overwrite
        language: python
        files: notebooks/
        minimum_pre_commit_version: 2.9.2
        types: [jupyter]
 
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
        files: src/
 
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ["--line-length", "88"]
        files: src/
 
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ["--max-line-length", "120"]
        additional_dependencies: ["flake8-bandit", "flake8-bugbear"]
        files: src/